name: Daily FII/DII Data Collection

on:
  schedule:
    # Runs at 6:30 PM IST (1:00 PM UTC) on weekdays
    - cron: '0 13 * * 1-5'
  workflow_dispatch: # Allows manual trigger

jobs:
  collect-fii-dii-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Collect FII/DII Data
        run: |
          echo "🕐 Starting FII/DII data collection..."
          
          # Use production domain instead of deployment URL to avoid auth issues
          VERCEL_URL="https://tradesmartmoney.vercel.app"
          
          echo "📡 Calling: $VERCEL_URL/api/cron/daily-fii-dii"
          
          # Try with bypass token if available
          HEADERS=""
          if [ -n "${{ secrets.VERCEL_BYPASS_TOKEN }}" ]; then
            HEADERS="-H 'x-vercel-protection-bypass: ${{ secrets.VERCEL_BYPASS_TOKEN }}'"
            echo "🔐 Using Vercel bypass token"
          fi
          
          # Call the endpoint with better headers and error handling
          response=$(curl -L -s -w "\n%{http_code}" -X POST \
            "$VERCEL_URL/api/cron/daily-fii-dii" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-FII-DII-Collector/1.0" \
            -H "Accept: application/json" \
            $HEADERS \
            --max-time 60 \
            --retry 3)
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "📊 Response Body: $body"
          echo "🔢 HTTP Code: $http_code"
          
          # Try GET method if POST fails
          if [ "$http_code" -ne 200 ]; then
            echo "🔄 Trying GET method instead..."
            response=$(curl -L -s -w "\n%{http_code}" -X GET \
              "$VERCEL_URL/api/cron/daily-fii-dii" \
              -H "User-Agent: GitHub-Actions-FII-DII-Collector/1.0" \
              -H "Accept: application/json" \
              $HEADERS \
              --max-time 60)
            
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | head -n -1)
            
            echo "📊 GET Response Body: $body"
            echo "🔢 GET HTTP Code: $http_code"
          fi
          
          # Check for success (200) or acceptable failure (500 means API ran but NSE failed)
          if [ "$http_code" -eq 200 ]; then
            echo "✅ FII/DII data collection successful!"
          elif [ "$http_code" -eq 500 ]; then
            echo "⚠️ API ran but data collection failed (likely NSE API issue)"
            echo "📄 Response: $body"
            # Don't exit with error for 500 - it means our API is working
            exit 0
          else
            echo "❌ FII/DII data collection failed!"
            echo "🐛 Debug info:"
            echo "   URL used: $VERCEL_URL/api/cron/daily-fii-dii"
            echo "   HTTP Code: $http_code"
            echo "   Response: $body"
            exit 1
          fi 